# Generated by Django 3.1.4 on 2020-12-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField()),
                ('favorite', models.BooleanField()),
                ('status', models.CharField(choices=[('HT', 'Hot'), ('CLD', 'Cold'), ('WRM', 'Warm')], default='WRM', max_length=20)),
                ('date_of_creating', models.DateField(auto_now_add=True)),
                ('place_of_creation', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.group')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.social')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RCVD', 'Received'), ('SNT', 'Sent'), ('DRFT', 'Draft')], max_length=20)),
                ('type', models.CharField(choices=[('RCVD', 'Received'), ('SNT', 'Sent'), ('DRFT', 'Draft')], max_length=20)),
                ('additionally', models.CharField(max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.user'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('place_of_creation', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='first.profile')),
                ('linked_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='first.profile')),
                ('linked_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RCVD', 'Received'), ('SKPD', 'Skipped'), ('RJCD', 'Rejected')], max_length=20)),
                ('type_of_call', models.CharField(choices=[('INCM', 'Incoming'), ('OTCM', 'Outcoming')], max_length=20)),
                ('additionally', models.CharField(max_length=100)),
                ('audio', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_user', models.CharField(max_length=100)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
                ('social_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.social')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.BooleanField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.contact')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.profile')),
            ],
        ),
    ]
